### ISSUE TITLE
how to install in windows 10?

### ISSUE THREAD

**Issue by wonb168** [0x0L/pgeon#2]
run `pip install .`, error:
 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pgeon
Failed to build pgeon
ERROR: Could not build wheels for pgeon, which is required to install pyproject.toml-based projects

**Comment by wonb168** [comment]
ERROR:
`(pgeon) E:\code\github\pgeon>pip install .
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Processing e:\code\github\pgeon
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
      Collecting scikit-build@ git+https://github.com/rdbisme/scikit-build.git@parse-setup-cfg
        Cloning https://github.com/rdbisme/scikit-build.git (to revision parse-setup-cfg) to c:\users\wang\appdata\local\temp\pip-install-9y47w7je\scikit-build_08fb989d731c41e9acc15bc01e0ff1a5
        Running command git clone --filter=blob:none --quiet https://github.com/rdbisme/scikit-build.git 'C:\Users\wang\AppData\Local\Temp\pip-install-9y47w7je\scikit-build_08fb989d731c41e9acc15bc01e0ff1a5'
        fatal: unable to access 'https://github.com/rdbisme/scikit-build.git/': Failed to connect to github.com port 443: Timed out
        error: subprocess-exited-with-error

        git clone --filter=blob:none --quiet https://github.com/rdbisme/scikit-build.git 'C:\Users\wang\AppData\Local\Temp\pip-install-9y47w7je\scikit-build_08fb989d731c41e9acc15bc01e0ff1a5' did not run successfully.
        exit code: 128

        See above for output.

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      git clone --filter=blob:none --quiet https://github.com/rdbisme/scikit-build.git 'C:\Users\wang\AppData\Local\Temp\pip-install-9y47w7je\scikit-build_08fb989d731c41e9acc15bc01e0ff1a5' did not run successfully.
      exit code: 128

      See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by rdbisme** [comment]
I think you are behind a proxy that is blocking connections to https on Github. Is that possible?

**Comment by wonb168** [comment]
> I think you are behind a proxy that is blocking connections to https on Github. Is that possible?

after add proxy, another error:
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pgeon
Failed to build pgeon
ERROR: Could not build wheels for pgeon, which is required to install pyproject.toml-based projects

**Comment by rdbisme** [comment]
I'll need more log, this is just the final part and it does not give any insight on the problem. Can you provide the full log?
