### ISSUE TITLE
`numeric` and `money` don't work on windows

### ISSUE THREAD

**Issue by rdbisme** [0x0L/pgeon#21]

**Comment by 0x0L** [comment]
https://github.com/0x0L/pgeon/blob/a0df7e57b4da237bfe9086740b37a554cb0396ac/src/builder/numeric.cc#L9

I don't think that's going to work :)

**Comment by rdbisme** [comment]
Do we need a proper int128 implementation?

**Comment by 0x0L** [comment]
I'd hope we can use arrow Decimal128 maybe... somehow... the proper underlying type is hidden in `arrow/util/int128_internal.h` which is of course not exposed
