### ISSUE TITLE
Proper version tag when releasing

### ISSUE THREAD

**Issue by 0x0L** [0x0L/pgeon#30]
The artifacts are produced with a 0.1 version number (see assets in Release too)

Also I'd need to force a proper rebuild after adding a tag

**Comment by rdbisme** [comment]
This is "intended" in the way `setuptools_scm`. What about sticking to semantic versioning, and considering all versions `<=1.0` unstable? 

So tagging `0.1` instead of `0.1a`. https://semver.org/#spec-item-4
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

This will make automatic tagging correct.

**Comment by 0x0L** [comment]
What is intended ? The current tag is 0.3b on my local machine, not on the CI

**Comment by rdbisme** [comment]
Yeah, sorry. I thought `setuptools_scm` was not able to parse the tag we were producing. This #31 should fix it.
