### ISSUE TITLE
Not really an issue, but a question...

### ISSUE THREAD

**Issue by prmoore77** [0x0L/pgeon#32]
Hello @0x0L and @rdbisme, thanks for this great work!

I was wondering how you produced the graph in image: https://github.com/0x0L/pgeon/blob/main/benchmarks/minute_bars.svg

Could you refer me to the type of graph used, as well as the tool used to generate it?

I appreciate it.

Thank you.

**Comment by 0x0L** [comment]
Hi @prmoore77 

All the code for the benchmark is in
https://github.com/0x0L/pgeon/tree/main/benchmarks

The graph is a kde plot made with the `seaborn` library

**Comment by prmoore77** [comment]
Thank you, @0x0L !
